name: Deploy Doc to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "doc"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build VitePress Site
        run: pnpm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './doc/lib'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
